### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#148]
We want a version against dev branch and one against master... then later we will also build the native installers against master.

**Comment by simlu** [comment]
Im thinking we can use bitrise

**Comment by simlu** [comment]
https://travis-ci.com

**Comment by simlu** [comment]
Finally got maven somewhat working. Travis here we come!

**Comment by simlu** [comment]
@funabab I think I'll merge this first... lots of files moving around for this one... we will have to fix our pull requests unfortunately, but thats gonna be easier that doing this again *sigh*...

**Comment by simlu** [comment]
Made very good progress on this! More to do though...

**Comment by simlu** [comment]
What I want to achieve here:
1) Add another qa branch
2) When pushing to dev it should trigger a build and upload zip file to s3... We then need to somewhere make the file location available
3) When tagging qa a github pre-release should be triggered 
4) When tagging master a github release should be triggered

Q: Can we induce a tag by creating a pre-release and then have the file attach to that release by the travis execution triggered?
Q: How do we submit the dev s3 url back to github?

I think we will get rid of the auto updater... thoughts?

**Comment by simlu** [comment]
Also: Version should be coming from git tag, need to add some maven tests, need to add jide key to Travis environment variables

**Comment by simlu** [comment]
Latest version of develop will now always be available at:
https://s3-us-west-2.amazonaws.com/voxelshop/build/develop/voxelshop-bin.zip

Remaining:
- add qa branch
- add and test qa/prod release hooks
- add tests to travis

**Comment by simlu** [comment]
Can we somehow check against the releases page if a new version is available?

**Comment by simlu** [comment]
I merged for now. What remains:
- move existing tests over so they run with ci
- Change the updater so it checks against the latest version of master (?)

**Comment by simlu** [comment]
Made some good headway in separating the tests out... more work needed. But this might be something where you can help as well @funabab

**Comment by funabab** [comment]
How can i come in.

**Comment by simlu** [comment]
Started working on more tests and already fixed a bunch of issues with the importers/exporter.

However the framework as problems with Travis... more investigation needed. Might have to switch away from junit testing...?  More investigation needed:

```
...
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.awt.HeadlessToolkit.createCustomCursor(HeadlessToolkit.java:251)
	at com.vitco.app.settings.VitcoSettings.<clinit>(VitcoSettings.java:90)
	... 38 more
```

**Comment by simlu** [comment]
This seems to be more or less working now. Still way more tests to add. Maybe you want to take a stab at the pnx one @funabab? Please review and approve pull request here: https://github.com/simlu/voxelshop/pull/222
