### ISSUE TITLE
VoxelShop crashes upon launching.

### ISSUE THREAD

**Issue by aytimothy** [simlu/voxelshop#226]
I've only downloaded VoxelShop fresh and both on the executable (Windows) and universal version, the first run always works fine, but anything after that results in this error and crash at launch:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'WindowManager': Invocation of init method failed; nested exception is java.lang.IndexOutOfBoundsException: Invalid index
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:394)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1448)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.vitco.Main.main(Main.java:68)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index
	at javax.swing.DefaultRowSorter.convertRowIndexToModel(Unknown Source)
	at sun.swing.FilePane$SortableListModel.getElementAt(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.getCellBounds(Unknown Source)
	at javax.swing.JList.getCellBounds(Unknown Source)
	at javax.swing.JList.ensureIndexIsVisible(Unknown Source)
	at sun.swing.FilePane.ensureIndexIsVisible(Unknown Source)
	at sun.swing.FilePane.doDirectoryChanged(Unknown Source)
	at sun.swing.FilePane.propertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.awt.Component.firePropertyChange(Unknown Source)
	at javax.swing.JFileChooser.setCurrentDirectory(Unknown Source)
	at com.vitco.util.components.dialog.components.FolderSelectModule.setSelectedFolder(FolderSelectModule.java:31)
	at com.vitco.util.components.dialog.components.FolderSelectModule.loadValue(FolderSelectModule.java:95)
	at com.vitco.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:268)
	at com.vitco.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:268)
	at com.vitco.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:268)
	at com.vitco.util.components.dialog.UserInputDialog.loadSerialization(UserInputDialog.java:255)
	at com.vitco.layout.content.menu.MainMenuLogic.registerLogic(MainMenuLogic.java:647)
	at com.vitco.layout.bars.MainMenuLinkage.buildBar(MainMenuLinkage.java:158)
	at com.vitco.layout.WindowManager.prepareBar(WindowManager.java:180)
	at com.vitco.layout.WindowManager$13.create(WindowManager.java:511)
	at com.jidesoft.action.DefaultDockableBarManager.a(Unknown Source)
	at com.jidesoft.action.DefaultDockableBarManager.loadInitialLayout(Unknown Source)
	at com.vitco.layout.WindowManager.init(WindowManager.java:523)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:346)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:299)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:132)
	... 14 more
```

I've tried updating my java version, reinstalling and checking for any locks on the files, but there seems to be nothing going on.

NB: This persists through reinstall on a per-version basis.

**Comment by simlu** [comment]
There should be a config folder .voxelshop 

Can you try deleting that and see if it launches after?

**Comment by aytimothy** [comment]
> There should be a config folder .voxelshop
>
> Can you try deleting that and see if it launches after?

Where is this folder located? In the `%appdata%` folder or in the base folder of the executable?

**Comment by simlu** [comment]
Should be in your home folder / appdata, depending on OS.

**Comment by simlu** [comment]
Seems to be a common issue... I should fix config corruption somehow...

**Comment by DaniAngione** [comment]
@simlu 
I was having this issue last night (latest build) and figured out how to fix it.  Turns out the .voxelshop folder is being created on the wrong folder. It's being created on the user folder (i.e: C:\Users\Username) instead of inside the %appdata% folder; moving it to the appdata (C:\Users\Username\AppData\Roaming) fixed the issue without having to delete it anymore
