### ISSUE TITLE
Crashes during Per Voxel export.

### ISSUE THREAD

**Issue by adambeltz** [simlu/voxelshop#271]
VoxelShop is crashing during export when Per Voxel is selected.  I have had this happen consistently, but only on certain models.

Here is the error log:

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at sun.java2d.Disposer.addRecord(Unknown Source)
	at sun.awt.image.BufImgSurfaceData.initRaster(Native Method)
	at sun.awt.image.BufImgSurfaceData.createDataIC(Unknown Source)
	at sun.awt.image.BufImgSurfaceData.createData(Unknown Source)
	at sun.awt.image.BufImgSurfaceManager.<init>(Unknown Source)
	at sun.awt.image.SurfaceManager.getManager(Unknown Source)
	at sun.java2d.SurfaceData.getPrimarySurfaceData(Unknown Source)
	at sun.java2d.SunGraphicsEnvironment.createGraphics(Unknown Source)
	at java.awt.image.BufferedImage.createGraphics(Unknown Source)
	at java.awt.image.BufferedImage.getGraphics(Unknown Source)
	at sun.swing.CachedPainter.paint0(Unknown Source)
	at sun.swing.CachedPainter.paint(Unknown Source)
	at com.sun.java.swing.plaf.windows.XPStyle$Skin.paintSkinRaw(Unknown Source)
	at com.sun.java.swing.plaf.windows.AnimationController.paintSkin(Unknown Source)
	at com.sun.java.swing.plaf.windows.XPStyle$Skin.paintSkin(Unknown Source)
	at com.sun.java.swing.plaf.windows.WindowsProgressBarUI.paintDeterminate(Unknown Source)
	at javax.swing.plaf.basic.BasicProgressBarUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

**Comment by simlu** [comment]
This is happening for large models. I have to see if I can optimize the export better. How much memory do you have and how much is voxelshop using? You could try starting it with more memory until I fix it, e.g. try

https://stackoverflow.com/questions/11654725/how-to-run-jar-through-terminal-with-more-ram-allocated-on-mac

**Comment by adambeltz** [comment]
I have 16gb and voxelshop is up to about 4.5gb when the export fails.  I haven't tried running it with more ram allocated.

**Comment by simlu** [comment]
I'll see what I can do to optimize the export
