### ISSUE TITLE
VoxelShop crashes on startup

### ISSUE THREAD

**Issue by epicdude312** [simlu/voxelshop#287]
I've been having an issue where VS crashes on startup. I get this error:
`
===================
2018-05-23 17-40-23
-------------------
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'WindowManager': Invocation of init method failed; nested exception is java.lang.IndexOutOfBoundsException: Invalid index
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:394)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1448)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.vitco.app.App.main(App.java:89)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index
	at javax.swing.DefaultRowSorter.convertRowIndexToModel(Unknown Source)
	at sun.swing.FilePane$SortableListModel.getElementAt(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.getCellBounds(Unknown Source)
	at javax.swing.JList.getCellBounds(Unknown Source)
	at javax.swing.JList.ensureIndexIsVisible(Unknown Source)
	at sun.swing.FilePane.ensureIndexIsVisible(Unknown Source)
	at sun.swing.FilePane.doDirectoryChanged(Unknown Source)
	at sun.swing.FilePane.propertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.awt.Component.firePropertyChange(Unknown Source)
	at javax.swing.JFileChooser.setCurrentDirectory(Unknown Source)
	at com.vitco.app.util.components.dialog.components.FolderSelectModule.setSelectedFolder(FolderSelectModule.java:31)
	at com.vitco.app.util.components.dialog.components.FolderSelectModule.loadValue(FolderSelectModule.java:95)
	at com.vitco.app.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:273)
	at com.vitco.app.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:273)
	at com.vitco.app.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:273)
	at com.vitco.app.util.components.dialog.UserInputDialog.loadSerialization(UserInputDialog.java:255)
	at com.vitco.app.layout.content.menu.MainMenuLogic.registerLogic(MainMenuLogic.java:659)
	at com.vitco.app.layout.bars.MainMenuLinkage.buildBar(MainMenuLinkage.java:176)
	at com.vitco.app.layout.WindowManager.prepareBar(WindowManager.java:177)
	at com.vitco.app.layout.WindowManager$13.create(WindowManager.java:511)
	at com.jidesoft.action.DefaultDockableBarManager.a(Unknown Source)
	at com.jidesoft.action.DefaultDockableBarManager.loadInitialLayout(Unknown Source)
	at com.vitco.app.layout.WindowManager.init(WindowManager.java:523)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:346)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:299)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:132)
	... 14 more
`

Reinstalling fixes the error, but it comes back after a couple times using VS.

**Comment by simlu** [comment]
This is due to corrupted config. I really need to fix this issue. I you can try deleting your settings file instead of reinstalling. Still not sure what is causing the corruption, but I'm assuming shutdown doesn't wait for write... 

Thanks for the report!

**Comment by epicdude312** [comment]
I can't seem to find any settings file. I've looked both in the installation folder and the JAR, and the only settings I've found are vitco settings.

**Comment by simlu** [comment]
It would be in your home folder

**Comment by epicdude312** [comment]
So, the folder where VoxelShop was extracted to? I don't see a settings file there -- maybe that's the problem.

**Comment by simlu** [comment]
No, in your user directory. I'm not sure which OS you're on. If it's Windows it would be under C:\Users\Username\AppData\Roaming

**Comment by simlu** [comment]
OSX would be ~

**Comment by epicdude312** [comment]
I've looked in the Roaming folder (I'm on Windows), and I still can't find any settings file. Stuck using MagicaVoxel for now.

**Comment by simlu** [comment]
I'll try to look into this more over the weekend! Thanks for the report!

**Comment by simlu** [comment]
@epicdude312 So the config file should be in `C:\Users\Username\.voxelshop\` - after you deleted it the program should work again. I'm still trying to find a good way to resolve this once and for all...

**Comment by simlu** [comment]
@epicdude312 And I can't reproduce this. If you could send me a copy of your config before you delete it, that would be great. You can find my contact info and email on blackflux.com
