### ISSUE TITLE
Crash on init

### ISSUE THREAD

**Issue by ghost** [simlu/voxelshop#302]
Due to a corrupted settings file.

The 'pref-004.ser' file:
[https://ufile.io/qc9wfxr4](https://ufile.io/qc9wfxr4)

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'WindowManager': Invocation of init method failed; nested exception is java.lang.IndexOutOfBoundsException: Invalid index
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:394)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1448)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.vitco.app.App.main(App.java:89)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index
	at javax.swing.DefaultRowSorter.convertRowIndexToModel(DefaultRowSorter.java:514)
	at sun.swing.FilePane$SortableListModel.getElementAt(FilePane.java:670)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1360)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI.getCellBounds(BasicListUI.java:952)
	at javax.swing.JList.getCellBounds(JList.java:1637)
	at javax.swing.JList.ensureIndexIsVisible(JList.java:1149)
	at sun.swing.FilePane.ensureIndexIsVisible(FilePane.java:1708)
	at sun.swing.FilePane.doDirectoryChanged(FilePane.java:1631)
	at sun.swing.FilePane.propertyChange(FilePane.java:1681)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8434)
	at javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:598)
	at com.vitco.app.util.components.dialog.components.FolderSelectModule.setSelectedFolder(FolderSelectModule.java:31)
	at com.vitco.app.util.components.dialog.components.FolderSelectModule.loadValue(FolderSelectModule.java:95)
	at com.vitco.app.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:273)
	at com.vitco.app.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:273)
	at com.vitco.app.util.components.dialog.BlankDialogModule.loadValue(BlankDialogModule.java:273)
	at com.vitco.app.util.components.dialog.UserInputDialog.loadSerialization(UserInputDialog.java:255)
	at com.vitco.app.layout.content.menu.MainMenuLogic.registerLogic(MainMenuLogic.java:683)
	at com.vitco.app.layout.bars.MainMenuLinkage.buildBar(MainMenuLinkage.java:176)
	at com.vitco.app.layout.WindowManager.prepareBar(WindowManager.java:177)
	at com.vitco.app.layout.WindowManager$13.create(WindowManager.java:511)
	at com.jidesoft.action.DefaultDockableBarManager.a(Unknown Source)
	at com.jidesoft.action.DefaultDockableBarManager.loadInitialLayout(Unknown Source)
	at com.vitco.app.layout.WindowManager.init(WindowManager.java:523)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:346)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:299)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:132)
	... 14 more
```

**Comment by panmaro** [comment]
I've got similar problem. 
This is the first run of this app, so there is no settings file.
There is [errorlog.txt](https://github.com/simlu/voxelshop/files/3861065/errorlog.txt) file.

**Comment by simlu** [comment]
I really need to improve the error message here, so that we at least know what's going on... (i.e. if a settings file is loaded, where it's located)

Thanks for reporting this. I'll try to take a look over the weekend!
