### ISSUE TITLE
Can't open Voxelshop

### ISSUE THREAD

**Issue by Robtherobe** [simlu/voxelshop#303]
I tried to open voxel shop and it never opened. I have never used it before so there is no settings file to delete. This is what is in the error log. I use mac os Catalina. Also, I'm using java 11.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.beans.factory.config.MethodInvokingFactoryBean#1' defined in class path resource [com/vitco/app/glue/config.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:591)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.vitco.app.App.main(App.java:89)
Caused by: java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.vitco.app.layout.LayoutLoader.loadLayout(LayoutLoader.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.beans.factory.config.MethodInvokingFactoryBean.doInvoke(MethodInvokingFactoryBean.java:162)
	at org.springframework.beans.factory.config.MethodInvokingFactoryBean.afterPropertiesSet(MethodInvokingFactoryBean.java:152)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
	... 12 more

**Comment by akoutsoulelos** [comment]
It's the same error as [here](https://github.com/simlu/voxelshop/issues/295). It seems that VoxelShop is having a problem while running on java 11. Try switching to an older version of java (version 8 seems to work good).

**Comment by Robtherobe** [comment]
After some looking, I've switched to it, and it works fine. Thank you very much

**Comment by kshitij5** [comment]
I'm having the same issue, even on Java 8! Any solution? or what is the minimum requirement?

**Comment by simlu** [comment]
@kshitij5 What error did you get on Java 8? Did you try deleting the settings file? It should work on Java 8

**Comment by follower** [comment]
For more information on this issue see: https://github.com/simlu/voxelshop/issues/295#issuecomment-700481983

**Comment by BerakaTula99** [comment]
how to install voxel shop on windows please 
comment installer voxel shop sur widows s'il vous plait

**Comment by BerakaTula99** [comment]
comment installer Voxel shop sur windows s'il vous plait
